Song replay on Itunes sample finish
GuyHadas/BillboardTopTen pull request #3
Opened 2016-10-26 04:57 UTC by AviWaiz

- feature for handling songs that have to play for several weeks, and will run longer than sample

2016-10-26 05:34 UTC, GuyHadas requested changes
@AviWaiz looks good, just some minor changes. When you commit those changes, ping me again by tagging me in a comment at the bottom. Then I'll review again and if all is good give a thumbs up.

2016-10-26 05:34 UTC, GuyHadas commented on frontend/components/home.jsx
> +
Extra space

2016-10-26 05:34 UTC, GuyHadas commented on frontend/components/home.jsx
> +    this.setState({currentTrackURL: this.state.currentTrackURL});
add spaces at the end and beginning of the object, reference the style in the setState above

2016-10-27 02:52 UTC, GuyHadas commented on frontend/components/home.jsx
> +    this.setState({ currentTrackURL: this.state.currentTrackURL });
One more thing, just add a comment here explaining what you're doing since it's confusing. Once you do that this is good to merge.

2016-10-27 20:23 UTC, AviWaiz reviewed
@GuyHadas added comment explaining logic behind the method

2016-10-28 04:03 UTC, GuyHadas commented
👍

2016-10-28 04:27 UTC, merged